apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: mzinga-lab4
  labels:
    app: webapp
    strategy: recreate
spec:
  selector:
    app: webapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
